---
date: "16/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("DT")

datatable(mtcars,
          extensions = 'Buttons',
          options = list(
            dom = 'Bfrtip',
            buttons = list(
              list(
                extend = 'collection',
                text = 'Filter',
                action = DT::JS("function ( e, dt, node, config ) {
                                   $.fn.dataTable.ext.search.push(
                                      function( settings, data, dataIndex ) {
                                         return data[0] == 'Mazda RX4'
                                      }
                                   );     
                                   dt.draw();
                                   $.fn.dataTable.ext.search.pop();
                                }")
              ),
              list(
                extend = 'collection',
                text = 'Restore',
                action = DT::JS("function ( e, dt, node, config ) {
                                   $.fn.dataTable.ext.search.pop();
                                   dt.draw();
                                }")
              )
            )
          )
)
```
